//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Savas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ayarlar
    {
        public int ID { get; set; }
        public string SAVASCIADI { get; set; }
        public string CANPUAN { get; set; }
        public string ATAK { get; set; }
        public string DEFANS { get; set; }
        public string KISAMESAFE { get; set; }
        public string UZUNMESAFE { get; set; }
    
        public virtual SAVA SAVA { get; set; }
    }
}
